data1 = """VI THE SHOEMAKER GOOD DAY SAID MONSIEUR DEFARGE LOOKING DOWN AT THE WHITE HEAD THAT BENT LOW OVER THE SHOEMAKING IT WAS RAISED FOR A MOMENT AND A VERY FAINT VOICE RESPONDED TO THE SALUTATION AS IF IT WERE AT A DISTANCE GOOD DAY YOU ARE STILL HARD AT WORK I SEE AFTER A LONG SILENCE THE HEAD WAS LIFTED FOR ANOTHER MOMENT AND THE VOICE REPLIED YESI AM WORKING THIS TIME A PAIR OF HAGGARD EYES HAD LOOKED AT THE QUESTIONER BEFORE THE FACE HAD DROPPED AGAIN THE FAINTNESS OF THE VOICE WAS PITIABLE AND DREADFUL IT WAS NOT THE FAINTNESS OF PHYSICAL WEAKNESS THOUGH CONFINEMENT AND HARD FARE NO DOUBT HAD THEIR PART IN IT ITS DEPLORABLE PECULIARITY WAS THAT IT WAS THE FAINTNESS OF SOLITUDE AND DISUSE IT WAS LIKE THE LAST FEEBLE ECHO OF A SOUND MADE LONG AND LONG AGO SO ENTIRELY HAD IT LOST THE LIFE AND RESONANCE OF THE HUMAN VOICE THAT IT AFFECTED THE SENSES LIKE A ONCE BEAUTIFUL COLOUR FADED AWAY INTO A POOR WEAK STAIN SO SUNKEN AND SUPPRESSED IT WAS THAT IT WAS LIKE A VOICE UNDERGROUND SO EXPRESSIVE IT WAS OF A HOPELESS AND LOST CREATURE THAT A FAMISHED TRAVELLER WEARIED OUT BY LONELY WANDERING IN A WILDERNESS WOULD HAVE REMEMBERED HOME AND FRIENDS IN SUCH A TONE BEFORE LYING DOWN TO DIE SOME MINUTES OF SILENT WORK HAD PASSED AND THE HAGGARD EYES HAD LOOKED UP AGAIN NOT WITH ANY INTEREST OR CURIOSITY BUT WITH A DULL MECHANICAL PERCEPTION BEFOREHAND THAT THE SPOT WHERE THE ONLY VISITOR THEY WERE AWARE OF HAD STOOD WAS NOT YET EMPTY I WANT SAID DEFARGE WHO HAD NOT REMOVED HIS GAZE FROM THE SHOEMAKER TO LET IN A LITTLE MORE LIGHT HERE YOU CAN BEAR A LITTLE MORE THE SHOEMAKER STOPPED HIS WORK LOOKED WITH A VACANT AIR OF LISTENING AT THE FLOOR ON ONE SIDE OF HIM THEN SIMILARLY AT THE FLOOR ON THE OTHER SIDE OF HIM THEN UPWARD AT THE SPEAKER WHAT DID YOU SAY YOU CAN BEAR A LITTLE MORE LIGHT"""
data2 = """"""
words1 = data1.split()
words2 = data2.split()

num_words_different = 0
num_chars_different = 0

for i in range(len(data1)):
    if not data1[i] == data2[i]:
        num_chars_different += 1

for i in range(len(words1)):
    if not words1[i] == words2[i]:
        num_words_different += 1

print("Number of characters that differ: " + str(num_chars_different))
print("Char error: " + str(num_chars_different / len(data1)))
print("Number of words that differ: " + str(num_words_different))
print("Word error: " + str(num_words_different / len(words1)))